package com.example.enums;

public enum ProfileStep {
    DEFAULT, NAME, SURNAME, PHONE, CAR_DETAIL, CAR_PRICE, UPDATE_CAR_DETAIL, UPDATE_CAR_PRICE, TAKE_CAR_STARTED_DATE, TAKE_CAR_FINISHED_DATE, TAKE_CAR_CAR_ID;
}
